//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersService.TestData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsersService.TestData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///      &quot;id&quot;: &quot;2564f7cb-ee65-444f-a40b-dd6b585aeea5&quot;,
        ///      &quot;firstName&quot;: &quot;Gomez&quot;,
        ///      &quot;lastName&quot;: &quot;Chaney&quot;,
        ///      &quot;age&quot;: 67,
        ///      &quot;gender&quot;: 1,
        ///      &quot;email&quot;: &quot;gomez.chaney@email.com&quot;,
        ///      &quot;address&quot;: {
        ///        &quot;id&quot;: &quot;3e5c846a-2c80-4a65-ad01-5c07df1bc38c&quot;,
        ///        &quot;street&quot;: &quot;Mill Avenue&quot;,
        ///        &quot;doorNumber&quot;: 32,
        ///        &quot;zipCode&quot;: &quot;5286-391&quot;,
        ///        &quot;city&quot;: &quot;Convent&quot;,
        ///        &quot;country&quot;: &quot;Tuvalu&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;f12ccd57-6a4e-4b46-bf6b-e9468e06c89b&quot;,
        ///      &quot;fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsersData {
            get {
                return ResourceManager.GetString("UsersData", resourceCulture);
            }
        }
    }
}
